/**
 * @nexus/bridge — Spec Template
 *
 * Templates de documentação técnica parametrizáveis.
 * Gera seções Markdown padronizadas: Overview, Architecture,
 * Data Model, API, Deployment, etc.
 *
 * @author Camilo Girardelli — Girardelli Tecnologia
 */

import { formatTable, formatSection } from "@nexus/core";

// ═══════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════

export type TemplateType = "microservice" | "monolith" | "mobile" | "full-stack" | "library";

export interface TemplateSection {
  title: string;
  content: string;
  level: number;
}

export interface TemplateConfig {
  projectName: string;
  templateType: TemplateType;
  actors: string[];
  features: string[];
  entities: string[];
  techStack: string[];
  integrations: string[];
  nfrs: string[];
}

// ═══════════════════════════════════════════════════════════════
// SPEC TEMPLATE
// ═══════════════════════════════════════════════════════════════

/**
 * Gera seções Markdown de spec a partir de templates parametrizados.
 *
 * @example
 * ```ts
 * const sections = SpecTemplate.generate({
 *   projectName: "SmartCollect",
 *   templateType: "microservice",
 *   actors: ["user", "admin", "system"],
 *   features: ["onboarding", "negociação", "compliance"],
 *   entities: ["debt", "payment", "user"],
 *   techStack: ["Python", "FastAPI", "Kafka", "PostgreSQL"],
 *   integrations: ["WhatsApp", "Telegram"],
 *   nfrs: ["High Availability", "Security"],
 * });
 * ```
 */
export class SpecTemplate {
  /**
   * Gera todas as seções da spec.
   */
  static generate(config: TemplateConfig): TemplateSection[] {
    const sections: TemplateSection[] = [];

    sections.push(this.overviewSection(config));
    sections.push(this.actorsSection(config));
    sections.push(this.featuresSection(config));
    sections.push(this.architectureSection(config));
    sections.push(this.dataModelSection(config));
    sections.push(this.apiSection(config));
    sections.push(this.integrationsSection(config));
    sections.push(this.deploymentSection(config));
    sections.push(this.nfrSection(config));
    sections.push(this.techStackSection(config));

    return sections;
  }

  /**
   * Renderiza todas as seções como Markdown.
   */
  static render(config: TemplateConfig): string {
    const sections = this.generate(config);
    return sections.map((s) => s.content).join("\n\n---\n\n");
  }

  // ─── SECTION GENERATORS ──────────────────────────────────

  private static overviewSection(config: TemplateConfig): TemplateSection {
    const content = [
      `# ${config.projectName} — Technical Specification`,
      "",
      `> Auto-generated by Nexus SpecGenerator`,
      "",
      `## 1. Overview`,
      "",
      `**Project:** ${config.projectName}`,
      `**Architecture:** ${config.templateType}`,
      `**Tech Stack:** ${config.techStack.join(", ") || "TBD"}`,
      `**Integrations:** ${config.integrations.join(", ") || "None"}`,
    ].join("\n");

    return { title: "Overview", content, level: 1 };
  }

  private static actorsSection(config: TemplateConfig): TemplateSection {
    const headers = ["Actor", "Description", "Channels"];
    const rows = config.actors.map((actor) => [
      actor,
      `${actor} persona`,
      this.inferChannels(actor, config.integrations),
    ]);

    const content = formatSection(
      "2. Actors & Personas",
      rows.length > 0 ? formatTable(headers, rows) : "No actors identified.",
      2,
    );

    return { title: "Actors", content, level: 2 };
  }

  private static featuresSection(config: TemplateConfig): TemplateSection {
    const headers = ["Feature", "Priority", "Complexity"];
    const rows = config.features.map((f, i) => [
      f,
      i < 3 ? "🔴 High" : i < 6 ? "🟡 Medium" : "🟢 Low",
      `${Math.min(5, Math.ceil((i + 1) / 2))}/5`,
    ]);

    const content = formatSection(
      "3. Features & Requirements",
      rows.length > 0 ? formatTable(headers, rows) : "No features identified.",
      2,
    );

    return { title: "Features", content, level: 2 };
  }

  private static architectureSection(config: TemplateConfig): TemplateSection {
    const diagram = this.generateC4Diagram(config);
    const content = [
      `## 4. Architecture (C4 Model)`,
      "",
      `### 4.1 System Context (Level 1)`,
      "",
      "```mermaid",
      diagram,
      "```",
    ].join("\n");

    return { title: "Architecture", content, level: 2 };
  }

  private static dataModelSection(config: TemplateConfig): TemplateSection {
    const headers = ["Entity", "Key Fields", "Relations"];
    const rows = config.entities.map((e) => [
      this.capitalize(e),
      `id, ${e}_name, status, created_at, updated_at`,
      this.inferRelations(e, config.entities),
    ]);

    const content = formatSection(
      "5. Data Model",
      rows.length > 0 ? formatTable(headers, rows) : "No entities identified.",
      2,
    );

    return { title: "Data Model", content, level: 2 };
  }

  private static apiSection(config: TemplateConfig): TemplateSection {
    const headers = ["Method", "Endpoint", "Description"];
    const rows: string[][] = [];

    for (const entity of config.entities.slice(0, 8)) {
      const plural = entity.endsWith("s") ? entity : `${entity}s`;
      rows.push(["GET", `/api/v1/${plural}`, `List all ${plural}`]);
      rows.push(["POST", `/api/v1/${plural}`, `Create ${entity}`]);
      rows.push(["GET", `/api/v1/${plural}/:id`, `Get ${entity} by ID`]);
      rows.push(["PUT", `/api/v1/${plural}/:id`, `Update ${entity}`]);
    }

    const content = formatSection(
      "6. API Design",
      rows.length > 0 ? formatTable(headers, rows) : "No API endpoints generated.",
      2,
    );

    return { title: "API", content, level: 2 };
  }

  private static integrationsSection(config: TemplateConfig): TemplateSection {
    const headers = ["Integration", "Protocol", "Direction"];
    const rows = config.integrations.map((int) => [
      int,
      this.inferProtocol(int),
      "Bidirectional",
    ]);

    const content = formatSection(
      "7. External Integrations",
      rows.length > 0 ? formatTable(headers, rows) : "No external integrations.",
      2,
    );

    return { title: "Integrations", content, level: 2 };
  }

  private static deploymentSection(config: TemplateConfig): TemplateSection {
    const isK8s = config.techStack.some((t) => ["Docker", "AWS"].includes(t));
    const infra = isK8s
      ? "Docker + Kubernetes (EKS/ECS) + ALB + RDS"
      : "Docker Compose + Nginx + PostgreSQL";

    const content = [
      `## 8. Deployment`,
      "",
      `**Infrastructure:** ${infra}`,
      "",
      `| Component | Technology |`,
      `|-----------|-----------|`,
      `| Runtime | Docker containers |`,
      `| Orchestration | ${isK8s ? "Kubernetes (EKS)" : "Docker Compose"} |`,
      `| Database | ${config.techStack.includes("PostgreSQL") ? "RDS PostgreSQL" : "Managed DB"} |`,
      `| Cache | ${config.techStack.includes("Redis") ? "ElastiCache Redis" : "In-memory"} |`,
      `| CI/CD | GitHub Actions |`,
      `| Monitoring | CloudWatch + Grafana |`,
    ].join("\n");

    return { title: "Deployment", content, level: 2 };
  }

  private static nfrSection(config: TemplateConfig): TemplateSection {
    const headers = ["Requirement", "Target", "Strategy"];
    const rows = config.nfrs.map((nfr) => [
      nfr,
      this.nfrTarget(nfr),
      this.nfrStrategy(nfr),
    ]);

    const content = formatSection(
      "9. Non-Functional Requirements",
      rows.length > 0 ? formatTable(headers, rows) : "No NFRs specified.",
      2,
    );

    return { title: "NFRs", content, level: 2 };
  }

  private static techStackSection(config: TemplateConfig): TemplateSection {
    const headers = ["Layer", "Technology", "Purpose"];
    const rows = config.techStack.map((tech) => [
      this.inferLayer(tech),
      tech,
      this.inferPurpose(tech),
    ]);

    const content = formatSection(
      "10. Technology Stack",
      rows.length > 0 ? formatTable(headers, rows) : "No stack defined.",
      2,
    );

    return { title: "Tech Stack", content, level: 2 };
  }

  // ─── HELPERS ─────────────────────────────────────────────

  private static generateC4Diagram(config: TemplateConfig): string {
    const lines: string[] = ["graph TB"];

    // Actors
    for (const actor of config.actors) {
      lines.push(`  ${actor}["👤 ${this.capitalize(actor)}"]`);
    }

    // System
    lines.push(`  system["🏗️ ${config.projectName}"]`);

    // Integrations
    for (const int of config.integrations) {
      const id = int.toLowerCase().replace(/\s+/g, "_");
      lines.push(`  ${id}["🔌 ${int}"]`);
      lines.push(`  system --> ${id}`);
    }

    // Actor connections
    for (const actor of config.actors) {
      lines.push(`  ${actor} --> system`);
    }

    // Database
    if (config.techStack.some((t) => ["PostgreSQL", "MongoDB"].includes(t))) {
      lines.push(`  db["🗄️ Database"]`);
      lines.push(`  system --> db`);
    }

    return lines.join("\n");
  }

  private static inferChannels(actor: string, integrations: string[]): string {
    if (actor === "user" || actor === "driver") return integrations.join(", ") || "API";
    if (actor === "admin") return "Web Portal";
    return "Internal API";
  }

  private static inferRelations(entity: string, allEntities: string[]): string {
    const common: Record<string, string[]> = {
      user: ["account", "order", "payment"],
      order: ["product", "payment", "user"],
      payment: ["invoice", "transaction", "user"],
      debt: ["payment", "transaction", "user"],
    };
    const related = common[entity] ?? [];
    return related.filter((r) => allEntities.includes(r)).join(", ") || "—";
  }

  private static inferProtocol(integration: string): string {
    if (["WhatsApp", "Telegram", "SMS"].includes(integration)) return "Webhook/API";
    if (["GitHub", "Jira"].includes(integration)) return "REST API";
    if (integration === "Slack") return "WebSocket/API";
    return "REST API";
  }

  private static nfrTarget(nfr: string): string {
    const targets: Record<string, string> = {
      "High Availability": "99.9% uptime",
      "Scalability": "10x growth",
      "Security": "OWASP Top 10",
      "Performance": "p99 < 200ms",
      "Observability": "100% coverage",
      "Multi-tenant": "Data isolation",
    };
    return targets[nfr] ?? "TBD";
  }

  private static nfrStrategy(nfr: string): string {
    const strategies: Record<string, string> = {
      "High Availability": "Multi-AZ, health checks, auto-scaling",
      "Scalability": "Horizontal scaling, message queues",
      "Security": "JWT, RBAC, encryption at rest, LGPD compliance",
      "Performance": "Caching, connection pooling, indexing",
      "Observability": "Structured logging, metrics, distributed tracing",
      "Multi-tenant": "Schema per tenant, row-level security",
    };
    return strategies[nfr] ?? "TBD";
  }

  private static inferLayer(tech: string): string {
    const layers: Record<string, string> = {
      "TypeScript": "Backend", "Python": "Backend", "React": "Frontend",
      "Flutter": "Mobile", "PostgreSQL": "Database", "MongoDB": "Database",
      "Redis": "Cache", "Kafka": "Messaging", "Docker": "Infrastructure",
      "AWS": "Cloud",
    };
    return layers[tech] ?? "Other";
  }

  private static inferPurpose(tech: string): string {
    const purposes: Record<string, string> = {
      "TypeScript": "Server-side logic, type safety",
      "Python": "AI/ML services, API handlers",
      "React": "Web interface, SPA",
      "Flutter": "Cross-platform mobile app",
      "PostgreSQL": "Primary relational data store",
      "MongoDB": "Document store, flexible schema",
      "Redis": "Session cache, rate limiting",
      "Kafka": "Event streaming, async processing",
      "Docker": "Containerization, deployment",
      "AWS": "Cloud hosting, managed services",
    };
    return purposes[tech] ?? tech;
  }

  private static capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
}
